### ISSUE TITLE
cannot reconnect when trying to reconnect

### ISSUE THREAD

**Issue by moT01** [stroveio/strove.io#370] opened 2020-04-16 20:29 UTC
I wanted to take some time to try and figure out why this is happening, get some screenshots,  and reproduce it before making an issue - but here it is for now...

What happened:
I started up an embedded strove project.
I left my computer... screen saver came on.
I came back maybe a half hour or more later.
When I opened up my computer the project showed a message, something like "click to reconnect" I think.
When I click to reconnect, it does not reconnect and just sits with a "trying to reconnect" message indefinitely.

I think that's pretty much how it went.

My thought was that my project went to "sleep" or something, because it appears that they do that after some time I think. If that's the case - perhaps a project could wake itself back up.

**Comment by AdamZaczek** [comment] 2020-04-16 20:52
Idle projects are stopped after a while but we should run them again and/or show a modal asking if we should run a project automatically after the user comes back. I or @MateuszOlek will take this one. Currently, this should be fixed refreshing the page.

Thanks!

**Comment by AdamZaczek** [comment] 2020-04-19 12:01
This turns out to be much harder to reproduce than expected as we made efforts to prevent staying in the editor when the project closes earlier and they work for me no matter what I try. Did it happen more than once?

Right now, the correct behavior is going back to the dashboard - this way it's clear that the project has been stopped but we consider making it come back to life automatically.

**Comment by AdamZaczek** [comment] 2020-04-20 22:46
I finally managed to reproduce this. It's a Google Cloud issue, most likely caused by greatly increased cloud demand.

Also, during the time of the issue, when Google Cloud seemed heavily overloaded project add times went up from 15 seconds to 124! 

While we can not fix the issue itself right now, I think we should monitor not just the request performance but also cloud performance and let users know when a cloud provider seems to have serious issues.

I'm closing this one, for now, @moT01 , thanks again for reporting!

**Closed** 2020-04-20 22:53 UTC
Labels: bug
